version: '3'

services:
  frontend:
    image: node:18
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    command: bash -c "npm install && npm start"
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:1337

  backend:
    image: node:18
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "1337:1337"
    command: bash -c "npm install && npm run develop"
    environment:
      - NODE_ENV=development 